#server:
#  port: 8888
#spring:
#  application:
#    name: config
#  profiles:
#    active: dev
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/lynnlovemin/SpringCloudLesson.git #配置git仓库地址
#          searchPaths: 第09课/config #配置仓库路径
#          username: ****** #访问git仓库的用户名
#          password: ****** #访问git仓库的用户密码
#      label: master #配置仓库的分支
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/