server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#      spring.cloud.gateway.discovery.locator.enabled：表示是否与服务发现组件（register）进行结合，
#      通过 serviceId（必须设置成大写）转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#      路由访问方式：http://Gateway_HOST:Gateway_PORT/ 大写的 serviceId/**，其中微服务应用名默认大写访问。 logging.level：日志配置策略


#  服务网关还有个作用就是接口的安全性校验，这个时候就需要通过 gateway 进行统一拦截。
#  Gateway 提供了多种 Filter 可供选择，如 GatewayFilter、GlobalFilter 等，不同的 Filter 的作用是不一样的，
#  GatewayFilter 处理单个路由的请求，而 GlobalFilter 根据名字大致就能知道其作用，它是一个全局 Filter，可以过滤所有路由请求，
#  本课以 GlobalFilter 为例，讲解如何通过 Filter 过滤 API 请求，从而达到鉴权的目的