eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: eurekaclient
#    spring.application.name 为该服务的名字，eureka.client.serviceUrl.defaultZone 的作用是指定注册中心的地址